twilio: # Twilio gateway configuration
  accountId: AC3b2da5047380221ab98e702e1fd52c34 
  accountToken: 3e222f7d2b6e9a5fa0747297a3f8da89
  numbers: # Numbers allocated in Twilio
    - +84915701560
    - # Second number
    - # Third number
    - # ...
    - # Nth number
  messagingServicesId: 
  localDomain: itpro.vn # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: # Size of push pending queue

#redphone:
#  authKey: # Deprecated

turn: # TURN server configuration
  secret: idontknow # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: "redis://localhost:6379/0"
  replicaUrls: ["redis://localhost:6379/10"]

directory: # Redis server configuration for directory cluster
  url: "redis://localhost:6379/1"
  replicaUrls: ["redis://localhost:6379/11"]

messageCache: # Redis server configuration for message store cache
  redis: {url: "redis://localhost:6379/2", replicaUrls: ["redis://localhost:6379/12"]}
  cacheRate: 1
  persistDelayMinutes: 10
  #url: "redis://localhost:6379/2"
  #replicaUrls: ["redis://localhost:6379/12"]

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: "signal"
  password: "khongbiet"
  url: "jdbc:postgresql://localhost:5432/messagedb"

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "signal"
  password: "khongbiet"
  url: "jdbc:postgresql://localhost:5432/accountsdb"

attachments: # AWS S3 configuration (born2go)
  accessKey: AKIAIJ77ZF5XUGDOCAIQ
  accessSecret: 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
  bucket: lalo-signal
  region: ap-southeast-1

profiles: # AWS S3 configuration
  accessKey: AKIAIJ77ZF5XUGDOCAIQ
  accessSecret: 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
  bucket: lalo-signal
  region: ap-southeast-1

apn: # Apple Push Notifications configuration
  bundleId: "com.born2go.signal"
  pushCertificate: "/home/born2go.com/src/signal-chat/Signal-Server/config/certNam.pem"
  pushKey: "-----BEGIN RSA PRIVATE KEY-----\n
MIIEpAIBAAKCAQEAwlNrNGj2Y16ULK0dQTdMcNDKRPOlg19sUjanWr48Mj6b/1FH\n
RqjoB1fLimoMmUfX1PeGqjG/st3TfEy/5I1wk/zCJAtux9kuZM6FA6/Bsm8GrmH/\n
/hd5o9NbF1TOFyTaBsIgJ/0wWmFgG9xHfgRCNAHFog1W+VBqgvUQzfH5APDEm9P7\n
3P3n05oNltZ71LZsXAtQyfoYx7mpxZj8JVzCXM7vDdC1n/JTwoD2MWDTPcOcfRoZ\n
3OM71eFDs4VXh2ChKbdh4fSCqflQxDvD+7E1ZeDpw5PxkurtmBv73R5wea0dNl95\n
qwrfN367S+yFe5JHGt3uhMBRgJcIIsDm4x48JQIDAQABAoIBAQCxKqikwcVQ11u0\n
V6hCWw5AFLs0ngYafhcd5WIy4xmynU5QOmQHUdspRqv1Z7ZQ0SU/ruSBqpWhl4hG\n
3RpeX21yHpFJl3rKjYE0uuyebdDkw0COIB7qI7Ds4bc80D6M7zYvzzDOBJHe9MRQ\n
4kXz6CILlEoA8rSG3QAeoRtPB/sDFObnCytZ5bXUR1zxG31fUJEgr6It/tPuVJAv\n
H90FjMhurXUVPjnuKsCnEjwEYDYuoasTFqVtYonLiuUkZBQRX9tEcmaq/y7ZB3oo\n
QwvikuZ0Cwt4wBk1IuX318UGX8PT4laBCWIzZwSGkvObhwMpKXBK+SsFduMn+ULn\n
vodUOkJJAoGBAPdvBtIqFDwVS2DzzHCW4RTySM/61SaABCFbO2nhcT470muEbskY\n
dIU4WgmcStsTQZBa/Cl8fEe4pkrNWvMtQQf+u+KP7Gu4L1uBRKTLDSoy1x20cJP8\n
9AHm1ruQLBE8x0f+UCD7zog6csGFwgJiVndlONYAFgBo3SwziHbGNTjbAoGBAMkN\n
tD4QGuayy0NQFJ21ah+u7QB7GEpODE8vKW2Z1YCZyNokEuDL67xHoHZ0oBUvjkkF\n
iCZlSWKlVocAo4E7Z1x7DYwrAkNquOrv3/EkQVLz053+LFz9PycmW+U6bPoZWksC\n
+9rp01f79fPVbMPUDaBoHVP1fFL3MjdPdAOMbe7/AoGBAMPq0YfPcb4xTkIySIpN\n
rWMchLLJdcTKUHro9h5cN4KDc5VWgzIPfxONDx3U9yCIGr3mjQt8WhugBWvtNjqe\n
doOSG8rFEvooGLdnn6ascHwdTV9j5FAJVlu7IAPboEj1ywUiROgY+eu7++lns7qX\n
isd3Co3H+6PPZHD/TOpe/v1JAoGAYDr28l2zAojBUU6bD4Etcky/k2NXlPkWWzAv\n
nA3tasgwonhxsLbp9gwyeYAIvxsr9zd2myoPne+VIrjjiY9tQY6ERXqwcqQ6Lfjy\n
LvEzcwjRWOW3RirQd2Scx3LXhj1sQksDURxp08r9Rd/5VyHAA+7RWsY841j96AtX\n
c/tbAvECgYBytYSwQ11GmQ8xsc/6beUEeZhPcRI+27s7gVZSRDFlC9LmClDaXCZy\n
OhMp2vXQGX+QeSD5+WiAR2Ep71Ym9knQbSFFj5IxntZEXIWlYRltf/5CevT/xvgF\n
Enng1r2cTRR84nf7C5ea+eRoVpFIbIvk4gnpc4pqfY7LQPIzsVN2cA==\n
-----END RSA PRIVATE KEY-----"

gcm: # GCM Configuration - FCM
  senderId: 490788795261
  apiKey: AAAAckVKs30:APA91bEfvdc0yE1nHHVW6nQwguuXRuXPtiWIYns34k9ANY7YSlbzZJtHg_9zweW5fnZtOi1Ks-EXUnCSzauNUr-wmKgQ5Nzu2LQJOgzb_0Og92SKFOVC-PyFz3dxljg0K52rLuzegMFRjFbUWH2Gn9ZqwICERVACjA

testDevices:
  [{number: "+84985916746", code: "999999"},{number: "+84915701560", code: "999999"},{number: "+8491654804281", code: "999999"},{number: "+84989144348", code: "999999"}]

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: config/example.keystore
      keyStorePassword: example
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
      #keyStorePath: config/example.keystore
      #keyStorePassword: example
      #validateCerts: true

logging:
  level: INFO
  #loggers:
  #  "org.whispersystems.textsecuregcm.push": DEBUG
  #  "org.whispersystems.textsecuregcm.controllers": DEBUG
  appenders:
    - type: file
      currentLogFilename: /tmp/textsecureshserver.log
      archivedLogFilenamePattern: /tmp/textsecureserver-%d.log.gz
      archivedFileCount: 5
    - type: console
      
