twilio: # Twilio gateway configuration
  accountId: AC3b2da5047380221ab98e702e1fd52c34 
  accountToken: 3e222f7d2b6e9a5fa0747297a3f8da89
  numbers: # Numbers allocated in Twilio
    - +84915701560
    - # Second number
    - # Third number
    - # ...
    - # Nth number
  messagingServicesId: 
  localDomain: itpro.vn # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: # Size of push pending queue

#redphone:
#  authKey: # Deprecated

turn: # TURN server configuration
  secret: idontknow # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: "redis://localhost:6379/0"
  replicaUrls: ["redis://localhost:6379/10"]

directory: # Redis server configuration for directory cluster
  url: "redis://localhost:6379/1"
  replicaUrls: ["redis://localhost:6379/11"]

messageCache: # Redis server configuration for message store cache
  redis: {url: "redis://localhost:6379/2", replicaUrls: ["redis://localhost:6379/12"]}
  cacheRate: 1
  persistDelayMinutes: 10
  #url: "redis://localhost:6379/2"
  #replicaUrls: ["redis://localhost:6379/12"]

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: "signal"
  password: "khongbiet"
  url: "jdbc:postgresql://localhost:5432/messagedb"

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "signal"
  password: "khongbiet"
  url: "jdbc:postgresql://localhost:5432/accountsdb"

attachments: # AWS S3 configuration
  accessKey: AKIAI4QMYJ7RMGYSHLJQ
  accessSecret: 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
  bucket: lalo-signal

profiles: # AWS S3 configuration
  accessKey: AKIAI4QMYJ7RMGYSHLJQ
  accessSecret: 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
  bucket: lalo-signal
  region: idontknow

apn: # Apple Push Notifications configuration
  bundleId: "com.born2go.signal"
  pushCertificate: "/home/born2go.com/src/signal-chat/Signal-Server/config/certNam.pem"
  pushKey: "/home/born2go.com/src/signal-chat/Signal-Server/config/keyNam.pem"

gcm: # GCM Configuration - faked
  senderId: 888789650296 
  apiKey: AIzaSyAsviyMy0kIe8uhCEfo8NbeqGoku7oOCi4

testDevices:
  [{number: "123456", code: "999"}]

